[package]
name = "skylines-fourier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
f32 = []

[dev-dependencies]
rand = "0.8.5"
approx = "0.5.1"
