[package]
name = "skylines-fourier-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
skylines-fourier = { path = "../skylines-fourier", version = "0.1.0" }
